---
title: "Lesson 6: One Shot Learning with R"
description: |
  One-shot learning is a machine learning algorithm using a limited amount of training set data to compare the similarities and differences between two images. This section will introduce you touUse R keras for building self define generator, building self define layer, building self define backend function. 
# author: []
# date: 2023-10-17
# output:
#   distill::distill_article:
#     self_contained: false

output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Example 1: Recognization of mnist number

Step 1 : Data Load

Read Data and Split into train、validate and test

```{r}
# library(keras)
# library(abind)
# mnist <- dataset_mnist("./images/mnist.npz")
# train_images <- mnist$train$x
# train_labels <- mnist$train$y
# set.seed(9478) 
# val_idx      <- sample( 1:nrow(train_images) , size = ceiling(0.2*nrow(train_images)) , replace = F ) 
# val_images   <- train_images[val_idx,,] 
# val_labels   <- train_labels[val_idx]  
# train_images <- train_images[-val_idx,,] 
# train_labels <- train_labels[-val_idx]  
# test_images  <- mnist$test$x 
# test_labels  <- mnist$test$y
```

